# Generated by Django 3.1.1 on 2020-09-18 03:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mindmap',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('describe', models.CharField(max_length=60)),
                ('md_file', models.FileField(upload_to='uploads_md/')),
                ('json_file', models.FileField(upload_to='uploads_json/')),
                ('edit_time', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
